# Generated by Django 5.2.5 on 2025-08-10 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_farmerprofile_user_alter_fieldprofile_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='farmer_id',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
