# Generated by Django 5.2.5 on 2025-08-12 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vettreatmentrecord',
            old_name='completed_on',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='vettreatmentrecord',
            old_name='notes',
            new_name='treatment_details',
        ),
        migrations.RenameField(
            model_name='vettreatmentrecord',
            old_name='request',
            new_name='vet_request',
        ),
        migrations.AddField(
            model_name='vettreatmentrecord',
            name='follow_up_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
