# Generated by Django 5.2.5 on 2025-08-12 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary', '0002_rename_completed_on_vettreatmentrecord_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vettreatmentrecord',
            old_name='date',
            new_name='completed_on',
        ),
        migrations.RenameField(
            model_name='vettreatmentrecord',
            old_name='vet_request',
            new_name='request',
        ),
    ]
