# Generated by Django 5.2.5 on 2025-08-06 13:06

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PickupLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('town', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='FieldSupervision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField()),
                ('supervision_date', models.DateField()),
                ('field_agent', models.ForeignKey(limit_choices_to={'user_type': 'FA'}, on_delete=django.db.models.deletion.CASCADE, related_name='supervised_by', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(limit_choices_to={'user_type': 'FD'}, on_delete=django.db.models.deletion.CASCADE, related_name='supervisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MilkCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('quantity_liters', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.10'))])),
                ('collection_date', models.DateField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('farmer', models.ForeignKey(limit_choices_to={'user_type': 'FR'}, on_delete=django.db.models.deletion.CASCADE, related_name='milk_collections', to=settings.AUTH_USER_MODEL)),
                ('field_agent', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'FA'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collected_milk', to=settings.AUTH_USER_MODEL)),
                ('pickup_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milk_collections', to='deliveries.pickuplocation')),
            ],
            options={
                'ordering': ['-collection_date'],
            },
        ),
    ]
