# Generated by Django 5.2.5 on 2025-08-06 20:00

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='milkcollection',
            name='price_per_liter',
            field=models.DecimalField(decimal_places=2, default=50.0, help_text='Price per liter at the time of collection', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.10'))]),
            preserve_default=False,
        ),
    ]
