# Generated by Django 5.2.5 on 2025-08-06 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0002_milkcollection_price_per_liter'),
    ]

    operations = [
        migrations.AddField(
            model_name='milkcollection',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
