# Generated by Django 5.2.4 on 2025-08-11 17:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0003_milkcollection_is_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milkcollection',
            name='collection_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
