# Generated by Django 5.2.4 on 2025-08-11 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0004_alter_milkcollection_collection_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milkcollection',
            name='collection_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
